Expediente/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.expediente.urls', namespace = 'expediente')),
    url(r'^accounts/login/', login, {'template_name': 'inicio_sesion.html'}, name='iniciar_sesion'),
    url(r'^logout/', logout_then_login, name='cerrar_sesion')
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

apps/expediente/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login_required
from apps.expediente.views.GeneralView import index, municipios, accesoDenegado
from apps.expediente.views.ResultadoExamenView import respuestaRegistrarResultadoExamen, listadoExamenes, buscarResultadoExamen,uploadResultadosEscaneados,actualizarRegResultExam,listadoArchivoResultados
from apps.expediente.views.SignoVitalView import ListadoSignosVitales, AgregarSignoVital, ModificarSignoVital, eliminarSignoVital
from apps.expediente.views.ExpedienteView import agregarExpediente, listadoExpedientes, modificarExpediente, eliminarExpediente, ReporteExpediente
from apps.expediente.views.ExamenMedicoView import listadoTipoExamen, listadoSolicitudExamen, nuevoTipoExamen
from apps.expediente.views.AlergiaView import AlergiaCreate, AlergiaList, AlergiaUpdate
from apps.expediente.views.CatalogoEnfermedadView import ListadoEnfermedades, AgregarEnfermedad, ModificarEnfermedad, eliminarEnfermedad
from apps.expediente.views.CatalogoEspecialidadEmpleadoView import ListadoEspecialidadesEmpleados, AgregarEspecialidadEmpleado, ModificarEspecialidadEmpleado, eliminarEspecialidadEmpleado
from apps.expediente.views.CatalogoMedicamentoView import ListadoMedicamentos, AgregarMedicamento, ModificarMedicamento, eliminarMedicamento
from apps.expediente.views.EmpleadoView import ListadoEmpleados, AgregarEmpleado, ModificarEmpleado, eliminarEmpleado
from apps.expediente.views.CatalogoTipoClinicaView import ListadoTipoClinicas, AgregarTipoClinica, ModificarTipoClinica, eliminarTipoClinica
from apps.expediente.views.ClinicaView import ListadoClinica, AgregarClinica, ModificarClinica, eliminarClinica
from apps.expediente.views.ConsultaView import ListadoConsultas, RegistrarConsulta, ModificarConsulta, eliminarConsulta
from apps.expediente.views.TurnoView import ListadoTurnos, AgregarTurno, ModificarTurno, eliminarTurno
from apps.expediente.views.OrdenExamenMedicoView import ListadoOrdenesExamen, AgregarOrdenExamen, ModificarOrdenExamen, eliminarOrdenExamen
from apps.expediente.views.ReferenciaMedicaView import listadoReferenciaMedica, registrarReferenciaMedica, ModificarReferenciaMedica, eliminarReferencia
from apps.expediente.views.ConstanciaMedicaView import ListadoConstanciasMedicas, AgregarConstanciaMedica, ModificarConstanciaMedica, eliminarConstancia
from apps.expediente.views.IncapacidadMedicaView import ListadoIncapacidadesMedicas, AgregarIncapacidadMedica, ModificarIncapacidadMedica, eliminarIncapacidad
from apps.expediente.views.RecetaMedicaView import ListadoRecetasMedicas, AgregarRecetaMedica, ModificarRecetaMedica, eliminarReceta

urlpatterns = [
    # General
    url(r'^$', login_required(index), name='inicio'),
    url(r'^ajax/municipios/$', login_required(municipios), name='ajax_municipios'),
    url(r'^acceso-denegado$', accesoDenegado, name='acceso_denegado'),

    # ResultadoExamen
    url(r'^examenes/resultados/registrar$', login_required(respuestaRegistrarResultadoExamen.as_view()), name='registrar_resultado_examen'),
    url(r'^examenes/resultados/listado$', login_required(listadoExamenes.as_view()), name='listado_examenes'),
    url(r'^examenes/resultados/buscar$', login_required(buscarResultadoExamen.as_view(template_name='expediente/examenes/buscar.html')), name='buscar_examen'),
    url(r'^examenes/resultados/subir$', login_required(uploadResultadosEscaneados.as_view()), name='resultados_escaneados'),
    url(r'^examenes/resultados/modificar/(?P<pk>\d+)$', login_required(actualizarRegResultExam.as_view()), name='modificar_examen'),
    url(r'^examenes/resultados/listado_archivos$', login_required(listadoArchivoResultados.as_view()), name='listado_archivos'),

    # SignoVital
    url(r'^signos-vitales/agregar$', login_required(AgregarSignoVital.as_view()), name='agregar_signo_vital'),
    url(r'^signos-vitales/listado$', login_required(ListadoSignosVitales.as_view()), name='listado_signos_vitales'),
    url(r'^signos-vitales/modificar/(?P<pk>\d+)/$', login_required(ModificarSignoVital.as_view()), name='modificar_signo_vital'),
    url(r'^signos-vitales/eliminar/(?P<id>\d+)/$', login_required(eliminarSignoVital), name='eliminar_signo_vital'),

    # ReferenciaMedica
    url(r'^referencias/agregar$', login_required(registrarReferenciaMedica.as_view()), name='registrar_referencia_medica'),
    url(r'^referencias/listado$', login_required(listadoReferenciaMedica.as_view()), name='listado_referencia_medica'),
    url(r'^referencias/modificar/(?P<pk>\d+)/$', login_required(ModificarReferenciaMedica.as_view()), name='modificar_referencia'),
    url(r'^referencias/eliminar/(?P<id>\d+)/$', login_required(eliminarReferencia), name='eliminar_referencia'),

    # Expediente
    url(r'^expedientes/agregar$', login_required(agregarExpediente), name='agregar_expediente'),
    url(r'^expedientes/listado$', login_required(listadoExpedientes.as_view()), name='listado_expedientes'),
    url(r'^expedientes/modificar/(?P<id>\d+)/$', login_required(modificarExpediente), name='modificar_expediente'),
    url(r'^expedientes/eliminar/(?P<id>\d+)/$', login_required(eliminarExpediente), name='eliminar_expediente'),
    url(r'^expedientes/reporte/(?P<pk>\d+)/$', login_required(ReporteExpediente.as_view()), name='reporte_expediente'),

    # TipoExamen
    url(r'^examenes/tipos/listado$', login_required(listadoTipoExamen.as_view()), name='listado_tipo_examen'),
    url(r'^examenes/tipos/registrar$', login_required(nuevoTipoExamen.as_view()), name='nuevo_tipo_examen'),
    url(r'^examenes/ordenes/listado$', login_required(listadoSolicitudExamen.as_view()), name='listado_orden_examen'),

    # Alergia
    url(r'^alergias/registrar', login_required(AlergiaCreate.as_view()), name='alergia_crear'),
    url(r'^alergias/listado', login_required(AlergiaList.as_view()), name='alergia_listar'),
    url(r'^alergias/modificar/(?P<pk>\d+)/$', login_required(AlergiaUpdate.as_view() ), name='alergia_modificar'),

    # Enfermedad
    url(r'^enfermedades/agregar$', login_required(AgregarEnfermedad.as_view()), name='agregar_enfermedad'),
    url(r'^enfermedades/listado$', login_required(ListadoEnfermedades.as_view()), name='listado_enfermedades'),
    url(r'^enfermedades/modificar/(?P<pk>\d+)/$', login_required(ModificarEnfermedad.as_view()), name='modificar_enfermedad'),
    url(r'^enfermedades/eliminar/(?P<id>\d+)/$', login_required(eliminarEnfermedad), name='eliminar_enfermedad'),

    # EspecialidadEmpleado
    url(r'^empleados/especialidades/agregar$', login_required(AgregarEspecialidadEmpleado.as_view()), name='agregar_especialidad_empleado'),
    url(r'^empleados/especialidades/listado$', login_required(ListadoEspecialidadesEmpleados.as_view()), name='listado_especialidades_empleados'),
    url(r'^empleados/especialidades/modificar/(?P<pk>\d+)/$', login_required(ModificarEspecialidadEmpleado.as_view()), name='modificar_especialidad_empleado'),
    url(r'^empleados/especialidades/eliminar/(?P<id>\d+)/$', login_required(eliminarEspecialidadEmpleado), name='eliminar_especialidad_empleado'),

    # Medicamento
    url(r'^medicamentos/agregar$', login_required(AgregarMedicamento.as_view()), name='agregar_medicamento'),
    url(r'^medicamentos/listado$', login_required(ListadoMedicamentos.as_view()), name='listado_medicamentos'),
    url(r'^medicamentos/modificar/(?P<pk>\d+)/$', login_required(ModificarMedicamento.as_view()), name='modificar_medicamento'),
    url(r'^medicamentos/eliminar/(?P<id>\d+)/$', login_required(eliminarMedicamento), name='eliminar_medicamento'),

    # Empleado
    url(r'^empleados/agregar$', login_required(AgregarEmpleado.as_view()), name='agregar_empleado'),
    url(r'^empleados/listado$', login_required(ListadoEmpleados.as_view()), name='listado_empleados'),
    url(r'^empleados/modificar/(?P<pk>\d+)/$', login_required(ModificarEmpleado.as_view()), name='modificar_empleado'),
    url(r'^empleados/eliminar/(?P<id>\d+)/$', login_required(eliminarEmpleado), name='eliminar_empleado'),

    # TipoClinica
    url(r'^clinicas/tipos/agregar$', login_required(AgregarTipoClinica.as_view()), name='agregar_tipo_clinica'),
    url(r'^clinicas/tipos/listado$', login_required(ListadoTipoClinicas.as_view()), name='listado_tipo_clinicas'),
    url(r'^clinicas/tipos/modificar(?P<pk>\d+)/$', login_required(ModificarTipoClinica.as_view()), name='modificar_tipo_clinica'),
    url(r'^clinicas/tipos/eliminar(?P<id>\d+)/$', login_required(eliminarTipoClinica), name='eliminar_tipo_clinica'),

    # Clinica
    url(r'^clinicas/agregar$', login_required(AgregarClinica.as_view()), name='agregar_clinica'),
    url(r'^clinicas/listado$', login_required(ListadoClinica.as_view()), name='listado_clinicas'),
    url(r'^clinicas/modificar/(?P<pk>\d+)/$', login_required(ModificarClinica.as_view()), name='modificar_clinica'),
    url(r'^clinicas/eliminar/(?P<id>\d+)/$', login_required(eliminarClinica), name='eliminar_clinica'),

    # Consulta
    url(r'^consulta/agregar$', login_required(RegistrarConsulta.as_view()), name='agregar_consulta'),
    url(r'^consulta/listado$', login_required(ListadoConsultas.as_view()), name='listado_consultas'),
    url(r'^consulta/modificar/(?P<pk>\d+)/$', login_required(ModificarConsulta.as_view()), name='modificar_consulta'),
    url(r'^consulta/eliminar/(?P<id>\d+)/$', login_required(eliminarConsulta), name='eliminar_consulta'),

    # Turno
    url(r'^turnos/agregar$', login_required(AgregarTurno.as_view()), name='agregar_turno'),
    url(r'^turnos/listado$', login_required(ListadoTurnos.as_view()), name='listado_turnos'),
    url(r'^turnos/modificar/(?P<pk>\d+)/$', login_required(ModificarTurno.as_view()), name='modificar_turno'),
    url(r'^turnos/eliminar/(?P<id>\d+)/$', login_required(eliminarTurno), name='eliminar_turno'),

    # OrdenExamen
    url(r'^examenes/ordenes/registrar$', login_required(AgregarOrdenExamen.as_view()), name='agregar_orden_examen'),

apps/expediente/views/EmpleadoView.py
from django.contrib.auth.decorators import user_passes_test
from django.http import Http404, HttpResponseRedirect
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView
from django.core.urlresolvers import reverse_lazy

from apps.expediente.permisos import Permisos
from apps.expediente.requests.EmpleadoRequest import EmpleadoForm, PersonaForm
from apps.expediente.models import Empleado, Persona

class ListadoEmpleados(ListView):
    model = Empleado
    template_name = 'expediente/empleados/listado.html'

    @method_decorator(user_passes_test(Permisos.solo_admin, login_url='/acceso-denegado'))
    def dispatch(self, *args, **kwargs):
        return super(ListadoEmpleados, self).dispatch(*args, **kwargs)

class AgregarEmpleado(CreateView):
    model = Empleado
    template_name = 'expediente/empleados/formulario.html'
    form_class = EmpleadoForm
    second_form_class = PersonaForm
    success_url = reverse_lazy('expediente:listado_empleados')

    def get_context_data(self, **kwargs):
        context = super(AgregarEmpleado, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(self.request.GET)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        empleado_form = self.form_class(request.POST)
        persona_form = self.second_form_class(request.POST)
        if empleado_form.is_valid() and persona_form.is_valid():
            empleado = empleado_form.save(commit=False)
            empleado.Persona = persona_form.save()
            empleado.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(
                form=empleado_form,
                form2=persona_form,
                empleado_errores=empleado_form.errors,
                persona_errores=persona_form.errors,
                mensaje_error='No se pudo guardar el Empleado. Por favor revise los datos.'
            ))

    @method_decorator(user_passes_test(Permisos.solo_admin, login_url='/acceso-denegado'))
    def dispatch(self, *args, **kwargs):
        return super(AgregarEmpleado, self).dispatch(*args, **kwargs)

class ModificarEmpleado(UpdateView):
    model = Empleado
    second_model = Persona
    form_class = EmpleadoForm
    second_form_class = PersonaForm
    template_name = 'expediente/empleados/formulario.html'
    success_url = reverse_lazy('expediente:listado_empleados')

    def get_context_data(self, **kwargs):
        context = super(ModificarEmpleado, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk', 0)
        empleado = self.model.objects.get(id=pk)
        persona = self.second_model.objects.get(id=empleado.Persona.id)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class(instance=persona)
        context['id'] = pk
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        id_empleado = kwargs['pk']
        empleado = self.model.objects.get(id=id_empleado)
        persona = self.second_model.objects.get(id=empleado.Persona.id)
        empleado_form = self.form_class(request.POST, instance=empleado)
        persona_form = self.second_form_class(request.POST, instance=persona)
        if empleado_form.is_valid() and persona_form.is_valid():
            empleado_form.save()
            persona_form.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return HttpResponseRedirect(self.get_success_url())

    @method_decorator(user_passes_test(Permisos.solo_admin, login_url='/acceso-denegado'))
    def dispatch(self, *args, **kwargs):
        return super(ModificarEmpleado, self).dispatch(*args, **kwargs)

def eliminarEmpleado(request, id):
    if not request.is_ajax():
        raise Http404("Error: Solicitud denegada - Esta acción solo se puede ejecutar desde una llamada Ajax.")
    if Permisos.solo_admin:
        return JsonResponse({'error': True, 'mensaje': 'Usted no tiene permiso para realizar esta acción'})
    empleado = Empleado.objects.get(id = id)
    if request.method == 'GET':
        empleado.delete()
        return JsonResponse({'error': False, 'mensaje': 'Se eliminó la Empleado ' + empleado.Persona.nombreCompleto()})
    return JsonResponse({'error': True, 'mensaje': 'No se pudo eliminar la Empleado ' + empleado.Persona.nombreCompleto()})

templates/expediente/empleados/especialidades/formulario.html
{% extends 'base/base.html' %}
{% block title %}Registro de Especialidad Empleado{% endblock %}
{% block content %}
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <h1 class="page-header"><i class="fa fa-file-text-o"></i> Registro de Especialidad Empleado</h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'expediente:inicio' %}"><i class="fa fa-home"></i> Inicio</a></li>
            <li><a href="{% url 'expediente:listado_especialidades_empleados' %}"><i class="fa fa-male"></i> Especialidades Empleados</a></li>
            <li><i class="fa fa-file-text-o"></i> Datos</li>
        </ol>
    </div>
</div>
<div class="row">
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Complete los datos requeridos</h3>
			</div>
			<div class="panel-body">
				<form method="post" autocomplete="off">
					{% csrf_token %}
					<fieldset>
						{{ form.as_p }}
						<div class="form-group">
							<button class="btn btn-primary" type="submit">
								<i class="fa fa-floppy-o"></i> Guardar
							</button>
							<a href="{% url 'expediente:listado_especialidades_empleados' %}" class="btn btn-danger">
								<i class="fa fa-times-circle"></i> Cancelar
							</a>
						</div>
					</fieldset>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/expediente/empleados/especialidades/listado.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block title %}Listado de Especialidades Empleados{% endblock %}
{% block css %}
<link href="{% static 'css/plugins/dataTables/dataTables.min.css' %}" rel="stylesheet" />
<link href="{% static 'css/plugins/dataTables/dataTables.bootstrap.min.css' %}" rel="stylesheet" />
<link href="{% static 'css/personalizaciones/datatable.css' %}" rel="stylesheet" />
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <h1 class="page-header"><i class="fa fa-male"></i> Listado de Especialidades Empleados</h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'expediente:inicio' %}"><i class="fa fa-home"></i> Inicio</a></li>
            <li><i class="fa fa-male"></i> Especialidades Empleados</li>
        </ol>
    </div>
</div>
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="dropdown pull-right">
            <a href="{% url 'expediente:agregar_especialidad_empleado' %}" class="btn btn-success">
                <i class="fa fa-plus-square"></i> Nuevo
            </a>
        </div>
    </div>
</div>
<hr>
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 table-responsive">
		{% if object_list %}
		<table class="table table-striped table-bordered table-hover table-responsive dataTable">
			<thead>
				<th>Tipo</th>
				<th></th>
			</thead>
			<tbody>
				{% for especialidad_empleado in object_list %}
				<tr>
					<td><a href="{% url 'expediente:modificar_especialidad_empleado' especialidad_empleado.id %}">{{ especialidad_empleado.tipoEspecialidad }}</a></td>
					<td><a class="btn btn-danger btn-sm EliminarRegistro" data-url="{% url 'expediente:eliminar_especialidad_empleado' especialidad_empleado.id %}"><i class="fa fa-trash"></i></a></td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% else %}
		<p>No Existen Registros de Especialidades Empleados</p>
		{% endif %}
	</div>
</div>
{% endblock %}
{% block js %}
<script src="{% static 'js/plugins/dataTables/dataTables.min.js' %}"></script>
<script src="{% static 'js/plugins/dataTables/dataTables.bootstrap.min.js' %}"></script>
<script src="{% static 'js/personalizaciones/datatable.js' %}"></script>
<script src="{% static 'js/eliminar-registro.js' %}"></script>
{% endblock %}